# Site setings
name: 'Javier Solorzano'
description: 'iOS Engineer & Designer'
meta_description: 'Javier Solorzano, iOS Engineer and Designer'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "Hello! My name is Javier Solorzano. I'm an iOS Engineer and Designer based in Louisiana. Thank you for visiting my blog."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://javsolo.dev/
mailchimp_url: # Fill with mailchimp URL if you starts a newsletter
ga_analytics: 

# Social links
github: 'jav-solo'
dribbble: 'jav-solo'
email: contact@javsolo.dev
resume_link: 'assets/files/resume.pdf'

# Navigation
navigation:
  - text: Blog
    url: /
  - text: Projects
    url: /projects
  - text: About
    url: /about
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
